imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        google_map_api_key: %google_map_api_key%
        pagerfanta_opts:
            previous_message: '&laquo;'
            next_message:     '&raquo;'
            dots_message:     ' … '

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                date:   Isics\Bundle\OpenMiamMiamBundle\Doctrine\ORM\Query\AST\Functions\Date

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }



# StofDoctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable:     true
            timestampable: true
            tree:          true

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Isics\Bundle\OpenMiamMiamUserBundle\Entity\User
    registration:
        confirmation:
            enabled: true
        form:
            type: open_miam_miam_user_registration
    profile:
        form:
            type: open_miam_miam_user_profile
    from_email:
        address:     %mailer_sender_address%
        sender_name: %mailer_sender_name%
    service:
        mailer: fos_user.mailer.twig_swift

# LiipImagineBundle Configuration
liip_imagine:
    filter_sets:
        s:
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        m:
            filters:
                thumbnail: { size: [200, 150], mode: outbound }
        l:
            filters:
                thumbnail: { size: [400, 300], mode: outbound }

# StfalconTinymceBundle
stfalcon_tinymce:
    include_jquery: true
    tinymce_jquery: true
    theme:
        simple:
            theme:     "modern"
            menubar:   false
            statusbar: false
            plugins:
                - "autolink lists textcolor"
            toolbar1: "bold,italic,underline,forecolor,styleselect,bullist,numlist,undo,redo,removeformat"
            style_formats:
                - { title: "Titre", block: "h2" }
                - { title: "Sous-titre", block: "h3" }
                - { title: "Paragraphe", block: "p" }

# Services
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [IsicsOpenMiamMiamBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node:       %node_path%
            node_paths: [%node_path%, %node_modules_path%]
            apply_to:   "\.less$"
        uglifycss:
            bin: %node_uglifycss_bin%
        uglifyjs2:
            bin: %node_uglifyjs_bin%
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
