Isics\Bundle\OpenMiamMiamUserBundle\Entity\User:
    properties:
        firstname:
            - NotNull: { groups: [Registration, Profile] }
            - Length:
                max: 128
                groups: [Registration, Profile]
        lastname:
            - NotNull: { groups: [Registration, Profile] }
            - Length:
                max: 128
                groups: [Registration, Profile]
        address1:
            - NotNull: { groups: [Registration, Profile] }
            - Length:
                max: 64
                groups: [Registration, Profile]
        address2:
            - Length:
                max: 64
                groups: [Registration, Profile]
        zipcode:
            - NotNull: { groups: [Registration, Profile] }
            - Length:
                max: 8
                groups: [Registration, Profile]
        city:
            - NotNull: { groups: [Registration, Profile] }
            - Length:
                max: 64
                groups: [Registration, Profile]
        phoneNumber:
            - Length:
                max: 16
                groups: [Registration, Profile]